
sonar.projectKey=RidECI-Legacy_mortal-kombat-statistic-service2
sonar.organization=rideci-legacy-1
sonar.projectName=mortal-kombat-statistic-service

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/application/**, **/core/**, **/domain/enums/**, **/domain/models/**, **/infrastructure/repositories/**, **/infrastructure/analytics/**, **/__init__.py, **/main.py, src/rideci/domain/services/AIAnalysisService.py,src/rideci/infrastructure/consumers/connection.py,src/rideci/infrastructure/consumers/main_worker.py,src/rideci/infrastructure/storage/S3StorageService.py

sonar.sourceEncoding=UTF-8