sonar.projectKey=mortal-kombat-stats-service
sonar.projectName=Mortal Kombat Stats Service
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=/usr/src/coverage.xml

sonar.exclusions=**/application/**, **/core/**, **/domain/enums/**, **/domain/models/**, **/infrastructure/repositories/**, **/infrastructure/analytics/**, **/__init__.py, **/main.py, src/rideci/domain/services/AIAnalysisService.py,src/rideci/infrastructure/consumers/connection.py,src/rideci/infrastructure/consumers/main_worker.py,src/rideci/infrastructure/storage/S3StorageService.py